descriptor_id: DOCKERFILE
descriptor_type: tooling_format
descriptor_flavors:
  - all_flavors # Applicable to CI in any language project
file_names_regex:
  - 'Dockerfile'
test_folder: docker
linters:
  # dockerfilelint
  - linter_name: dockerfilelint
    name: DOCKERFILE_DOCKERFILELINT
    linter_url: https://github.com/replicatedhq/dockerfilelint
    linter_rules_url: https://github.com/replicatedhq/dockerfilelint#checks-performed
    linter_rules_configuration_url: https://github.com/replicatedhq/dockerfilelint#configuring
    config_file_name: .dockerfilelintrc
    cli_config_arg_name: ""
    examples:
      - "dockerfilelint Dockerfile"
    install:
      npm:
        - dockerfilelint
  # Hadolint
  - linter_name: hadolint
    name: DOCKERFILE_HADOLINT
    linter_url: https://github.com/hadolint/hadolint
    linter_rules_url: https://github.com/hadolint/hadolint#rules
    linter_image_url: https://hadolint.github.io/hadolint/img/cat_container.png
    linter_rules_configuration_url: https://github.com/hadolint/hadolint#configure
    linter_rules_inline_disable_url: https://github.com/hadolint/hadolint#inline-ignores
    config_file_name: .hadolint.yml
    examples:
      - "hadolint Dockerfile"
      - "hadolint -c .dockerfilelintrc Dockerfile"
    install:
      dockerfile:
        - FROM hadolint/hadolint:latest-alpine as dockerfile-lint
        - COPY --from=dockerfile-lint /bin/hadolint /usr/bin/hadolint
    ide:
      atom:
        - name: linter-hadolint
          url: https://atom.io/packages/linter-hadolint
      vscode:
        - name: hadolint
          url: https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint
  # docker-label-inspector
  - linter_name: docker-label-inspector
    name: DOCKERFILE_DLI
    linter_url: https://github.com/garethr/docker-label-inspector
    linter_rules_url: https://github.com/garethr/docker-label-inspector#linter
    linter_rules_configuration_url: https://github.com/garethr/docker-label-inspector#linter
    cli_executable: 'dli'
    cli_lint_extra_args:
      - "lint"
      - "--dockerfile"
    examples:
      - "dli lint --dockerfile Dockerfile"
    install:
      dockerfile:
        - RUN pip install -e "git+https://github.com/volkc/docker-label-inspector.git@master#egg=docker-label-inspector"
  # docker-label-inspector
  - linter_name: docker-label-inspector-validate
    name: DOCKERFILE_DLI_VALIDATE
    linter_url: https://github.com/garethr/docker-label-inspector
    linter_rules_url: https://github.com/garethr/docker-label-inspector#linter
    linter_rules_configuration_url: https://github.com/garethr/docker-label-inspector#linter
    cli_executable: 'dli'
    cli_lint_extra_args:
      - "validate"
      - "--dockerfile"
    cli_config_arg_name: '--schema'
    config_file_name: .docker-label-inspector-schema.json
    examples:
      - "dli validate --dockerfile Dockerfile --schema .docker-label-inspector-schema.json"
    install:
      dockerfile:
        - RUN pip install -e "git+https://github.com/volkc/docker-label-inspector.git@master#egg=docker-label-inspector"
